[package]
name        = "serde"
version     = "0.1.0"
description = "A modular C++26 package"
license     = "Apache-2.0"
standard    = "c++23"

[toolchain]
default = "llvm@22.1.8"

[lib]
path = "src/json/json.cppm"

[build]
default-profile = "debug"
dialect_cxxflags = ["-fno-exceptions"]
sources = ["src/**/*.cppm", "third_party/simdjson/simdjson.cpp"]
defines = ["SIMDJSON_EXCEPTIONS=0", "nssv_CONFIG_NO_EXCEPTIONS=1"]

[targets.serde]
kind = "lib"

[targets.benchmark_serde_json]
kind = "bin"
main = "benchmark/serde_json.cpp"

[targets.benchmark_serde_json_alloc]
kind = "bin"
main = "benchmark/serde_json_alloc.cpp"

[targets.benchmark_serde_json_wide]
kind = "bin"
main = "benchmark/serde_json_wide.cpp"

[targets.benchmark_simdjson]
kind = "bin"
main = "benchmark/simdjson.cpp"

[targets.benchmark_serde_toml]
kind = "bin"
main = "benchmark/serde_toml.cpp"

[targets.benchmark_serde_toml_alloc]
kind = "bin"
main = "benchmark/serde_toml_alloc.cpp"

[targets.benchmark_tomlplusplus]
kind = "bin"
main = "benchmark/tomlplusplus.cpp"
